on:
  push:
    branches:
      - main
name: Test Manually
jobs:
  order:
    name: place-an-order-by-trigger
    runs-on: ubuntu-latest
    environment: SALTALK_AUTH
    steps:
      - name: Check out this repo
        uses: actions/checkout@master

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installing package list
        run: apt list --installed    
      
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  

      - name: Install Chromium browser, xvfb
        run: sudo apt-get install -y chromium-browser xvfb

       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: |
          pip install requests webdriver-manager
          pip install -r requirements.txt   

      - name: Run the selenium script
        run: |
              cd src
              python main.py
        env:
          SALTALK_ID: ${{ secrets.SALTALK_ID }}
          SALTALK_PASSWORD: ${{ secrets.SALTALK_PASSWORD }}
